"""Third  migration

Revision ID: 28505727691b
Revises: 4f91d7c40e76
Create Date: 2024-03-19 20:39:52.698445

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "28505727691b"
down_revision = "4f91d7c40e76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
